export const L = {
  // App
  APP_NAME: 'VisaFlow AI',
  APP_NAME_SHORT: 'VisaAI',
  TAGLINE: 'Automate Your Global Journey',

  // Auth
  LOGIN: 'Log In',
  SIGNUP: 'Sign Up',
  SIGN_IN: 'Sign In',
  REGISTER: 'Register',
  WELCOME_BACK: 'Welcome Back',
  CREATE_ACCOUNT: 'Create Account',
  FORGOT_PASSWORD: 'Forgot Password',
  RESET_PASSWORD: 'Reset Password',

  // Navigation
  DASHBOARD: 'Dashboard',
  ELIGIBILITY: 'Eligibility',
  CHATBOT: 'Chatbot',
  DOCUMENTS: 'Documents',
  SCHEDULER: 'Scheduler',
  TRACKER: 'Tracker',
  TRACKING_SIM: 'Tracking Sim',
  APPLICATIONS: 'Applications',
  SETTINGS: 'Settings',
  SUPPORT: 'Support',
  ADMIN: 'Admin Dashboard',

  // Actions
  SUBMIT: 'Submit',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  DOWNLOAD: 'Download',
  UPLOAD: 'Upload',
  SEND: 'Send',
  BACK: 'Back',
  NEXT: 'Next',
  EDIT: 'Edit',
  VIEW: 'View Details',
  VIEW_ALL: 'View All',
  EXPORT: 'Export Report',
  REFRESH: 'Refresh',
  SEARCH: 'Search',
  CLOSE: 'Close',

  // Feature labels
  CHECK_ELIGIBILITY: 'Check Eligibility',
  START_ASSESSMENT: 'Start Assessment',
  START_APPLICATION: 'Start Application',
  BOOK_CONSULTATION: 'Book AI Consultation',
  CONTACT_US: 'Contact Us',
  NEW_CONSULTATION: 'New Consultation',
  LAUNCH_ASSISTANT: 'Launch AI Assistant',
  VIEW_LOCATION: 'View Location',
  RESCHEDULE: 'Reschedule',
  DOWNLOAD_RECEIPT: 'Download Receipt',
  CONFIRM_BOOKING: 'Confirm Booking',
  NEW_TICKET: 'New Ticket',
  MY_TICKETS: 'My Tickets',
  SUBMIT_TICKET: 'Submit Ticket',
  ENCRYPT_SAVE: 'Encrypt & Save to Vault',
  WATCH_DEMO: 'Watch Demo',
  GET_EARLY_ACCESS: 'Get Early Access',
  TALK_TO_SALES: 'Talk to Sales',
  EXPLORE_FEATURE: 'Explore Feature',
  UPGRADE: 'Upgrade',
  SHARE: 'Share',
  SAVE_PROGRESS: 'Save Progress',

  // Status
  LOADING: 'Loading...',
  NO_DATA: 'No data available',
  NETWORK_ERROR: 'Network error. Please try again.',
  SESSION_EXPIRED: 'Session expired. Please log in again.',

  // Headings
  MY_APPOINTMENTS: 'My Appointments',
  APPOINTMENT_SCHEDULER: 'Appointment Scheduler',
  DOCUMENT_VAULT: 'Secure Document Vault',
  ELIGIBILITY_CHECKER: 'Visa Eligibility Checker',
  SUPPORT_TICKETS: 'Support Tickets',
  ADMIN_DOC_REVIEW: 'Document Review',
  NOTIFICATIONS: 'Notifications',
};
