export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  USER_DASHBOARD: '/user-dashboard',
  ADMIN_DASHBOARD: '/admin-dashboard-overview',
  ADMIN_DOC_REVIEW: '/admin-document-review',
  CHATBOT: '/ai-visa-chatbot',
  ELIGIBILITY_CHECKER: '/visa-eligibility-checker',
  ELIGIBILITY_RESULTS: '/eligibility-results-suggestions',
  APPOINTMENT_SCHEDULER: '/visa-appointment-scheduler',
  DOCUMENT_VAULT: '/document-vault-upload-system',
  PROGRESS_TRACKER: '/visa-progress-tracker',
  TRACKING_SIM: '/tracking-simulation',
  SUPPORT_TICKETS: '/support-tickets',
  KNOWLEDGE_MGMT: '/visa-knowledge-management',
  SCRAPER_MONITOR: '/scraper-monitoring-dashboard',
  APPROVAL_WORKFLOW: '/approval-workflow',
  ACTIVITY_LOGS: '/activity-logs',
  VISA_MARKETPLACE: '/visa-marketplace',
  VISA_DETAILS: '/visa/:id',
  APPLY_VISA: '/apply/:visa_id',
  MY_APPLICATIONS: '/my-applications',
};
